---
glob: "**/*.{html,text,js}{+*,}.erb"
exclude:
  - 'app/views/application/_analyticstracking.html.erb'
  - '**/vendor/**/*'
  - '**/node_modules/**/*'
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
  Rubocop:
    enabled: true
    rubocop_config:
      require: standard
      inherit_gem:
        standard: config/base.yml
      inherit_from: .erb-lint_rubocop.yml
      AllCops:
        DisabledByDefault: true
