language: ruby
bundler_args: --without development assets
rvm:
  - 1.9.3
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
branches:
  only:
    - master

