language: ruby
bundler_args: --without development
rvm:
  - 1.9.3
before_install:
  - psql -c 'CREATE ROLE vagrant NOSUPERUSER CREATEDB NOCREATEROLE INHERIT LOGIN;' -U postgres
  - psql -c 'CREATE DATABASE benmorrall_test OWNER vagrant;' -U postgres
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake travis
branches:
  only:
    - master
    - wip/travispassing

