language: ruby
bundler_args: --without development assets
rvm:
  - 1.9.3
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake travis
branches:
  only:
    - master

